spring.datasource.url=jdbc:postgresql://localhost:5432/mind_nest_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aws.access-key=AKIAS252V4DSZDGEWR2D
aws.secret-key=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
